# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data\window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sideBox = QtWidgets.QGroupBox(self.centralwidget)
        self.sideBox.setGeometry(QtCore.QRect(0, 0, 251, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.sideBox.setFont(font)
        self.sideBox.setObjectName("sideBox")
        self.uploadBoxLabel = QtWidgets.QLabel(self.sideBox)
        self.uploadBoxLabel.setGeometry(QtCore.QRect(15, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.uploadBoxLabel.setFont(font)
        self.uploadBoxLabel.setObjectName("uploadBoxLabel")
        self.disciplineBoxLabel = QtWidgets.QLabel(self.sideBox)
        self.disciplineBoxLabel.setGeometry(QtCore.QRect(15, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.disciplineBoxLabel.setFont(font)
        self.disciplineBoxLabel.setWordWrap(True)
        self.disciplineBoxLabel.setObjectName("disciplineBoxLabel")
        self.competencyBoxLabel = QtWidgets.QLabel(self.sideBox)
        self.competencyBoxLabel.setGeometry(QtCore.QRect(15, 95, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.competencyBoxLabel.setFont(font)
        self.competencyBoxLabel.setObjectName("competencyBoxLabel")
        self.label_4 = QtWidgets.QLabel(self.sideBox)
        self.label_4.setGeometry(QtCore.QRect(15, 119, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.backButton = QtWidgets.QPushButton(self.sideBox)
        self.backButton.setGeometry(QtCore.QRect(20, 512, 211, 31))
        self.backButton.setObjectName("backButton")
        self.forwButton = QtWidgets.QPushButton(self.sideBox)
        self.forwButton.setGeometry(QtCore.QRect(20, 550, 211, 31))
        self.forwButton.setObjectName("forwButton")
        self.label_15 = QtWidgets.QLabel(self.sideBox)
        self.label_15.setGeometry(QtCore.QRect(15, 145, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.uploadBox = QtWidgets.QGroupBox(self.centralwidget)
        self.uploadBox.setGeometry(QtCore.QRect(250, 0, 551, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.uploadBox.setFont(font)
        self.uploadBox.setVisible(True)
        self.uploadBox.setObjectName("uploadBox")
        self.study_planUploadBox = QtWidgets.QGroupBox(self.uploadBox)
        self.study_planUploadBox.setGeometry(QtCore.QRect(20, 30, 511, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.study_planUploadBox.setFont(font)
        self.study_planUploadBox.setObjectName("study_planUploadBox")
        self.study_planPathLabel = QtWidgets.QLabel(self.study_planUploadBox)
        self.study_planPathLabel.setGeometry(QtCore.QRect(20, 30, 471, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.study_planPathLabel.setFont(font)
        self.study_planPathLabel.setObjectName("study_planPathLabel")
        self.study_planUploadButton = QtWidgets.QPushButton(self.study_planUploadBox)
        self.study_planUploadButton.setGeometry(QtCore.QRect(20, 60, 101, 23))
        self.study_planUploadButton.setObjectName("study_planUploadButton")
        self.rpdUploadBox = QtWidgets.QGroupBox(self.uploadBox)
        self.rpdUploadBox.setGeometry(QtCore.QRect(20, 150, 511, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rpdUploadBox.setFont(font)
        self.rpdUploadBox.setObjectName("rpdUploadBox")
        self.rpdPathLabel = QtWidgets.QLabel(self.rpdUploadBox)
        self.rpdPathLabel.setGeometry(QtCore.QRect(20, 30, 471, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.rpdPathLabel.setFont(font)
        self.rpdPathLabel.setObjectName("rpdPathLabel")
        self.rpdUploadButton = QtWidgets.QPushButton(self.rpdUploadBox)
        self.rpdUploadButton.setGeometry(QtCore.QRect(20, 60, 101, 23))
        self.rpdUploadButton.setObjectName("rpdUploadButton")
        self.createButton = QtWidgets.QPushButton(self.uploadBox)
        self.createButton.setGeometry(QtCore.QRect(20, 280, 151, 31))
        self.createButton.setObjectName("createButton")
        self.uploadStatusLabel = QtWidgets.QLabel(self.uploadBox)
        self.uploadStatusLabel.setGeometry(QtCore.QRect(180, 290, 341, 16))
        self.uploadStatusLabel.setText("")
        self.uploadStatusLabel.setObjectName("uploadStatusLabel")
        self.disciplineBox = QtWidgets.QGroupBox(self.centralwidget)
        self.disciplineBox.setGeometry(QtCore.QRect(250, 0, 551, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.disciplineBox.setFont(font)
        self.disciplineBox.setVisible(False)
        self.disciplineBox.setObjectName("disciplineBox")
        self.dispComboBox = QtWidgets.QComboBox(self.disciplineBox)
        self.dispComboBox.setGeometry(QtCore.QRect(20, 50, 405, 22))  # !!
        self.dispComboBox.setMaxVisibleItems(10)
        self.dispComboBox.setObjectName("dispComboBox")
        self.dispComboLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispComboLabel.setGeometry(QtCore.QRect(20, 30, 171, 16))
        self.dispComboLabel.setObjectName("dispComboLabel")
        self.dispNameLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispNameLabel.setGeometry(QtCore.QRect(20, 80, 171, 16))
        self.dispNameLabel.setObjectName("dispNameLabel")
        self.dispNameEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispNameEdit.setGeometry(QtCore.QRect(20, 100, 511, 20))
        self.dispNameEdit.setObjectName("dispNameEdit")
        self.dispFieldLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispFieldLabel.setGeometry(QtCore.QRect(20, 130, 171, 16))
        self.dispFieldLabel.setObjectName("dispFieldLabel")
        self.dispFieldEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispFieldEdit.setGeometry(QtCore.QRect(20, 150, 511, 20))
        self.dispFieldEdit.setObjectName("dispFieldEdit")
        self.dispProfileLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispProfileLabel.setGeometry(QtCore.QRect(20, 180, 171, 16))
        self.dispProfileLabel.setObjectName("dispProfileLabel")
        self.dispProfileEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispProfileEdit.setGeometry(QtCore.QRect(20, 200, 511, 20))
        self.dispProfileEdit.setObjectName("dispProfileEdit")
        self.dispInstituteLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispInstituteLabel.setGeometry(QtCore.QRect(20, 230, 171, 16))
        self.dispInstituteLabel.setObjectName("dispInstituteLabel")
        self.dispInstituteEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispInstituteEdit.setGeometry(QtCore.QRect(20, 250, 511, 20))
        self.dispInstituteEdit.setObjectName("dispInstituteEdit")
        self.dispFormLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispFormLabel.setGeometry(QtCore.QRect(20, 280, 171, 16))
        self.dispFormLabel.setObjectName("dispFormLabel")
        self.dispFormEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispFormEdit.setGeometry(QtCore.QRect(20, 300, 511, 20))
        self.dispFormEdit.setObjectName("dispFormEdit")
        self.dispProgLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispProgLabel.setGeometry(QtCore.QRect(20, 330, 171, 16))
        self.dispProgLabel.setObjectName("dispProgLabel")
        self.dispProgEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispProgEdit.setGeometry(QtCore.QRect(20, 350, 511, 20))
        self.dispProgEdit.setObjectName("dispProgEdit")
        self.dispCathLabel = QtWidgets.QLabel(self.disciplineBox)
        self.dispCathLabel.setGeometry(QtCore.QRect(20, 380, 171, 16))
        self.dispCathLabel.setObjectName("dispCathLabel")
        self.dispCathEdit = QtWidgets.QLineEdit(self.disciplineBox)
        self.dispCathEdit.setGeometry(QtCore.QRect(20, 400, 511, 20))
        self.dispCathEdit.setObjectName("dispCathEdit")
        self.dispPartBox = QtWidgets.QGroupBox(self.disciplineBox)
        self.dispPartBox.setGeometry(QtCore.QRect(20, 430, 211, 80))
        self.dispPartBox.setObjectName("dispPartBox")
        self.dispPartBaseButton = QtWidgets.QRadioButton(self.dispPartBox)
        self.dispPartBaseButton.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.dispPartBaseButton.setObjectName("dispPartBaseButton")
        self.dispPartVarButton = QtWidgets.QRadioButton(self.dispPartBox)
        self.dispPartVarButton.setGeometry(QtCore.QRect(10, 50, 151, 17))
        self.dispPartVarButton.setObjectName("dispPartVarButton")
        self.dispObligBox = QtWidgets.QGroupBox(self.disciplineBox)
        self.dispObligBox.setGeometry(QtCore.QRect(240, 430, 241, 80))
        self.dispObligBox.setObjectName("dispObligBox")
        self.dispObligTrueButton = QtWidgets.QRadioButton(self.dispObligBox)
        self.dispObligTrueButton.setGeometry(QtCore.QRect(10, 30, 151, 17))
        self.dispObligTrueButton.setObjectName("dispObligTrueButton")
        self.dispObligFalseButton = QtWidgets.QRadioButton(self.dispObligBox)
        self.dispObligFalseButton.setGeometry(QtCore.QRect(10, 50, 121, 17))
        self.dispObligFalseButton.setObjectName("dispObligFalseButton")
        self.dispShowButton = QtWidgets.QPushButton(self.disciplineBox)
        self.dispShowButton.setGeometry(QtCore.QRect(430, 45, 101, 31))
        self.dispShowButton.setEnabled(False)
        self.dispShowButton.setObjectName("dispShowButton")
        self.competencyBox = QtWidgets.QGroupBox(self.centralwidget)
        self.competencyBox.setGeometry(QtCore.QRect(250, 0, 551, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.competencyBox.setFont(font)
        self.competencyBox.setVisible(False)
        self.competencyBox.setObjectName("competencyBox")
        self.compAddButton = QtWidgets.QPushButton(self.competencyBox)
        self.compAddButton.setGeometry(QtCore.QRect(10, 30, 31, 31))
        self.compAddButton.setObjectName("compAddButton")
        self.compDelButton = QtWidgets.QPushButton(self.competencyBox)
        self.compDelButton.setGeometry(QtCore.QRect(43, 30, 31, 31))
        self.compDelButton.setObjectName("compDelButton")
        self.compSaveButton = QtWidgets.QPushButton(self.competencyBox)
        self.compSaveButton.setGeometry(QtCore.QRect(76, 30, 111, 31))
        self.compSaveButton.setEnabled(False)
        self.compSaveButton.setObjectName("compSaveButton")
        self.compScrollArea = QtWidgets.QScrollArea(self.competencyBox)
        #self.compScrollArea.setGeometry(QtCore.QRect(10, 70, 531, 521))
        self.compScrollArea.move(10, 70)
        self.compScrollArea.setFixedWidth(531)
        self.compScrollArea.setMinimumHeight(520)
        self.compScrollArea.setWidgetResizable(True)
        self.compScrollArea.setObjectName("compScrollArea")
        self.compScrollAreaWidgetContents = QtWidgets.QWidget()
        #self.compScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 529, 519))
        self.compScrollAreaWidgetContents.setObjectName("compScrollAreaWidgetContents")
        self.compScrollArea.setWidget(self.compScrollAreaWidgetContents)
        self.downloadBox = QtWidgets.QGroupBox(self.centralwidget)
        self.downloadBox.setGeometry(QtCore.QRect(250, 0, 551, 601))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.downloadBox.setFont(font)
        self.downloadBox.setVisible(False)
        self.downloadBox.setObjectName("downloadBox")
        self.rpdDownloadBox = QtWidgets.QGroupBox(self.downloadBox)
        self.rpdDownloadBox.setGeometry(QtCore.QRect(20, 30, 511, 111))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rpdDownloadBox.setFont(font)
        self.rpdDownloadBox.setObjectName("rpdDownloadBox")
        self.downloadPathLabel = QtWidgets.QLabel(self.rpdDownloadBox)
        self.downloadPathLabel.setGeometry(QtCore.QRect(20, 30, 471, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.downloadPathLabel.setFont(font)
        self.downloadPathLabel.setObjectName("downloadPathLabel")
        self.downloadPathButton = QtWidgets.QPushButton(self.rpdDownloadBox)
        self.downloadPathButton.setGeometry(QtCore.QRect(20, 60, 101, 23))
        self.downloadPathButton.setObjectName("downloadPathButton")
        self.downloadButton = QtWidgets.QPushButton(self.downloadBox)
        self.downloadButton.setGeometry(QtCore.QRect(20, 160, 151, 31))
        self.downloadButton.setObjectName("downloadButton")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sideBox.setTitle(_translate("MainWindow", "Этапы создания"))
        self.uploadBoxLabel.setText(_translate("MainWindow", "1. Загрузка файлов"))
        self.disciplineBoxLabel.setText(_translate("MainWindow", "2. Информация о дисциплине"))
        self.competencyBoxLabel.setText(_translate("MainWindow", "3. Компетенции"))
        self.label_4.setText(_translate("MainWindow", "4. Разделы дисциплины"))
        self.backButton.setText(_translate("MainWindow", "Вернуться назад"))
        self.forwButton.setText(_translate("MainWindow", "Далее"))
        self.label_15.setText(_translate("MainWindow", "5. Формирование документа"))
        self.uploadBox.setTitle(_translate("MainWindow", "Загрузка файлов"))
        self.study_planUploadBox.setTitle(_translate("MainWindow", "Учебный план"))
        self.study_planPathLabel.setText(_translate("MainWindow", "<Файл не выбран>"))
        self.study_planUploadButton.setText(_translate("MainWindow", "Выбрать файл"))
        self.rpdUploadBox.setTitle(_translate("MainWindow", "Шаблон рабочей программы"))
        self.rpdPathLabel.setText(_translate("MainWindow", "<Файл не выбран>"))
        self.rpdUploadButton.setText(_translate("MainWindow", "Выбрать файл"))
        self.createButton.setText(_translate("MainWindow", "Загрузить файлы"))
        self.disciplineBox.setTitle(_translate("MainWindow", "Информация о дисциплине"))
        self.dispComboLabel.setText(_translate("MainWindow", "Выберите дисциплину:"))
        self.dispNameLabel.setText(_translate("MainWindow", "Название дисциплины"))
        self.dispFieldLabel.setText(_translate("MainWindow", "Направление подготовки"))
        self.dispProfileLabel.setText(_translate("MainWindow", "Профиль подготовки"))
        self.dispInstituteLabel.setText(_translate("MainWindow", "Институт"))
        self.dispFormLabel.setText(_translate("MainWindow", "Форма обучения"))
        self.dispProgLabel.setText(_translate("MainWindow", "Программа подготовки"))
        self.dispCathLabel.setText(_translate("MainWindow", "Кафедра"))
        self.dispPartBox.setTitle(_translate("MainWindow", "Базовая/Вариативная часть"))
        self.dispPartBaseButton.setText(_translate("MainWindow", "Базовая"))
        self.dispPartVarButton.setText(_translate("MainWindow", "Вариативная"))
        self.dispObligBox.setTitle(_translate("MainWindow", "Обязательная/По выбору"))
        self.dispObligTrueButton.setText(_translate("MainWindow", "Обязательная"))
        self.dispObligFalseButton.setText(_translate("MainWindow", "По выбору"))
        self.dispShowButton.setText(_translate("MainWindow", "Показать"))
        self.competencyBox.setTitle(_translate("MainWindow", "Компетенции"))
        self.compAddButton.setText(_translate("MainWindow", "+"))
        self.compDelButton.setText(_translate("MainWindow", "-"))
        self.compSaveButton.setText(_translate("MainWindow", "Сохранить"))
        self.downloadBox.setTitle(_translate("MainWindow", "Формирование документа"))
        self.rpdDownloadBox.setTitle(_translate("MainWindow", "Сохранение документа"))
        self.downloadPathLabel.setText(_translate("MainWindow", "<Файл не выбран>"))
        self.downloadPathButton.setText(_translate("MainWindow", "Выбрать путь"))
        self.downloadButton.setText(_translate("MainWindow", "Сформировать"))
        